# File valnode0.toml

[parity]
chain = "./data/genesis.json"
base_path = "./data/valnode0"

[network]
port = 30300
discovery = true
interface = "local"

[rpc]
disable=true

[websockets]
disable=true


[account]
password = ["config/valnode0.pwd"]

[mining]
#engine_signer = ""
reseal_on_txs = "none"
force_sealing = true
extra_data = "Parity"
